### ISSUE TITLE
ingame credtickethandler not working

### ISSUE THREAD

**Issue by ctimko1493** [Michal2SAB/Stick-Arena-Private-Server#2]
As stated above I inserted your credtickethandler into my src\ballistickemu\Lobby\handlers and it doesn't work when I login and go to shop it doesnt do the whole random cred like it should

**Comment by ctimko1493** [comment]
Also I need help with turning the source files into a .jar

**Comment by Michal2SAB** [comment]
If I remember right, you also need to have stickpacketmaker edited to include the handler in the first place etc. And possibly one other class.

If you did it all correct, then you have to create an event on your database. The event would change every user's ticket from 0 to 1 or from -1 to 0 (I forgot what it is when it's availabele, check it) every 8 hours or whatever

**Comment by ctimko1493** [comment]
Last issue (hopefully), now I'm getting a manifest file while compiling, i've tried to compile as a new project and it failed due to numerous errors but as a open project it worked fine just getting a manifest error when I try to run the server

**Comment by Michal2SAB** [comment]
Compile it with netbeans

**Comment by ctimko1493** [comment]
Netbeans is the one giving me the manifest error after compiling

**Comment by Michal2SAB** [comment]
You should check the logs or something in netbeans. I remember something like this happening to me too but I fixed it eventually. I don't remember what it was.

You can copy/paste the full error message here

**Comment by ctimko1493** [comment]
after adding the manifest file manually I now get 

Error: Unable to initialize main class ballistickemu.Main
caused by: Java.lang.NoClassDefFoundError: org/apache/mina/core/service/iohandler

**Comment by ctimko1493** [comment]
Alright kill me later and am sorry for being such a pain in the ass, I have everything running now, the jar, the credticket, but when I try to connect to the 588 swf it hangs on "checking for updates" everything else works as it should

**Comment by Michal2SAB** [comment]
If you're using eac's or tac's 588 SWF then all files like "settings588b.ini", "upgradevalues588.ini", "MapEditorTiles.csv" and "com" folder with "languagefilter.ini" inside should be located in the same folder as the SWF. If it's some other then it should be in "localhost/stickarena/". Localhost being your server or website. 

Alternatively something I did with dimensions.swf was make the game load with vars in index.php. Instead of dimensions.swf, it'd be something like dimensions.swf?phpURL=stick_arena.php&localFilePath=/stickarena/. But I think it only worked on a VPS.

Also check if you have "check_version.php" or "version.php" or something similar in the folder too. It doesn't do anything unless you want it to seriously check for newer versions, so the file can just be one line "result=success" or anything really.

**Comment by ctimko1493** [comment]
I'm using the SWF provided with your files, I couldn't find any other 588 SWF anywhere online, 
and I have all my files under C:\xampp\htdocs\stickarena

![image](https://user-images.githubusercontent.com/131619078/235221148-91e05ead-33fd-4719-87b7-12d93fe0fd46.png)

**Comment by ctimko1493** [comment]
and I have all my files under C:\xampp\htdocs\stickarena

**Comment by ctimko1493** [comment]
![image](https://user-images.githubusercontent.com/131619078/235220341-34080ea2-a3e9-4841-99b9-59c04991f06a.png)

**Comment by ctimko1493** [comment]
also is this what the swf should look like? 
![image](https://user-images.githubusercontent.com/131619078/235329523-60592d58-c201-4175-ae6d-ac3369de264b.png)

**Comment by Michal2SAB** [comment]
Well, yes.. honestly if you don't care about having a blue head in your server or all spinners, just get the 558 one. 588 is protected and unless you know how to bypass it, you won't do much

**Comment by ctimko1493** [comment]
How hard is it to bypass exactly? I have like 15 people rooting for me to get the 588 working XD

**Comment by andre-jar** [comment]
I got a working dimensions and 588 client now on my local host server. If this is still important to you guys I can maybe upload in the next few days or so. I also got all of the bugs you mentioned fixed(also working map download/upload). I just need to get it into a more refined state so that I can upload it.

**Comment by Leeskjold** [comment]
> I got a working dimensions and 588 client now on my local host server. If this is still important to you guys I can maybe upload in the next few days or so. I also got all of the bugs you mentioned fixed(also working map download/upload). I just need to get it into a more refined state so that I can upload it.

I would love that, it sounds great!
