### ISSUE TITLE
"Zombie" Games and Lobby not Correctly Updating

### ISSUE THREAD

**Issue by MGLFlex** [Michal2SAB/Stick-Arena-Private-Server#5]
Hello, 

Stick Arena Private Server is running pretty swell. We even got FAC to work by changing the local IP to the IP of the server host. However, couple pretty game breaking issues. 
1. When a host leaves a custom game, the game they created is not properly deregistering in the server (probably issue with communication between client and server). This usually happens when a host leaves their game while other players are also in the same game. It also does not always correctly kick out the other players who joined. This leaves the game active for upwards of days to even weeks, with no one actually inside the game. But when joined, the host will be in the top left corner, invulnerable to any attacks. If left up for long periods of time, it can cause the servers to lag and even at times crash.
2. Not all online players are visible in lobby to everyone. For some reason, only the person who most recently logged in can accurately see everyone who is currently online (also probably a communication issue). This means that even if there are 2 people in the same server, it shows one person that they're the only user online, meaning that you can't even see what the other player is typing because they aren't appearing as "online" on your screen.
3. When a game is created, the first one will start at 5:00, but subsequent games will start at 4:30. I suspect this is due to the fact that in the original game, there was a system in place that would offset each game to start 30 seconds later in order for the post game stat board to show for 30 seconds, however private server doesn't have this so if you join when a game is in the post game stats, you will join the map and be able to move, but you can't hit anyone who is in the credits screen.

Any help would be greatly appreciated.

**Comment by Michal2SAB** [comment]
> Hello,
> 
> Stick Arena Private Server is running pretty swell. We even got FAC to work by changing the local IP to the IP of the server host. However, couple pretty game breaking issues.
> 
> 1. When a host leaves a custom game, the game they created is not properly deregistering in the server (probably issue with communication between client and server). This usually happens when a host leaves their game while other players are also in the same game. It also does not always correctly kick out the other players who joined. This leaves the game active for upwards of days to even weeks, with no one actually inside the game. But when joined, the host will be in the top left corner, invulnerable to any attacks. If left up for long periods of time, it can cause the servers to lag and even at times crash.
> 2. Not all online players are visible in lobby to everyone. For some reason, only the person who most recently logged in can accurately see everyone who is currently online (also probably a communication issue). This means that even if there are 2 people in the same server, it shows one person that they're the only user online, meaning that you can't even see what the other player is typing because they aren't appearing as "online" on your screen.
> 3. When a game is created, the first one will start at 5:00, but subsequent games will start at 4:30. I suspect this is due to the fact that in the original game, there was a system in place that would offset each game to start 30 seconds later in order for the post game stat board to show for 30 seconds, however private server doesn't have this so if you join when a game is in the post game stats, you will join the map and be able to move, but you can't hit anyone who is in the credits screen.
> 
> Any help would be greatly appreciated.

These are some of the issues I talked about and suggested fixes for some of them in the README part. 

1. is likely happening because the situation where a host leaves the game is not even handled in the first place. Should have some kind of listener or whatever for when the game creator leaves, and then send a kick packet to the other players, with a custom message. Unless there is a specific, unique packet for that in the sa client (I forgot, but I doubt it), then you can just send that to players.

2. is likely an issue where new clients are not sending information that they logged in, to other clients. Or that the user that was already in the lobby, doesn't actually listen for new lobby appearances all the time, meaning only reading the data once after logging in. Could also be that the packets responsible for this process are structured wrong.

3. has something to do with inconsistency in the code I believe. I think I remember there being different round times in different parts of the code, but I could be wrong. They are in seconds by the way, so don't look for "4:30" or "5:00" in the code, rather look for "300" or "300-30" and stuff like that. 

The reason you can't hit anyone who is in the credits screen is because they have not really spawned yet (according to them). In SA I believe, the client that is being hit has to send that information to the attacker and not the other way around, in order for the hit to count, which is why godmode and other things always worked. Just like it has to send a lobby appearance packet, after logging in, otherwise you can be invisible. A terrible practice, but it can be changed. You generally want stuff like that to be handled by the server, not the client.

---

I don't know if any of this was helpful, but those are just some things I remember from messing with the server years ago. Some of these are easy fixes, but if I were you, I'd look for better version of ballistickemu. I've seen one that is an improved version of this one and a node.js one. The node.js one is smoother and less buggy, but has 0 game logic, only lobby.

I've stopped improving this server cause I just have 0 interest in the game now. Good luck!

**Comment by MGLFlex** [comment]
Appreciate you Michal. We are currently using the updated version by andre-jar, only reason I couldn't send the issue ticket there is because he is pulling from your project so it doesn't allow me to. Also I figured all the past issues were already here anyways so I decided to give it a shot. Some of the fixes were already implemented by him but it's still a bit clunky and we have lots of stuff to figure out. I will write another comment to let you know how things are going in the near future.

**Comment by andre-jar** [comment]
@MGLFlex I forgot to tick the box for the possiblity to create issues. It should work now. Can you reopen an issue in the fork now? I can have a look at the issues in the next few days. The thing with the userlist not properly getting updated is something I have noticed as well during testing. It is a bug left from the original project that I have not fixed, because I thought it would only sporadically appear.
